# Generated by Django 4.1.2 on 2023-05-19 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tracks",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traveler",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="tracking",
            field=models.ManyToManyField(
                related_name="mark_tracking", to="tracking.tracks"
            ),
        ),
    ]
