# Generated by Django 4.1.2 on 2023-05-19 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mark",
            old_name="tracking",
            new_name="track",
        ),
    ]
