# Generated by Django 4.1.2 on 2023-05-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_rename_tracking_mark_track"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mark",
            name="track",
        ),
        migrations.AlterField(
            model_name="tracks",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
