CITY_HOTELS = {
    'Shigar': ['Hotel Shigar Palace', 'Shigar Luxury Resort'],
    'Mansehra': ['Mansehra Resort', 'Hilltop Hotel'],
    'Dera Ismail Khan': ['Dera Grand Hotel', 'City View Inn'],
    'Shangla': ['Shangla Retreat', 'Mountain View Hotel'],
    'Paharpur': ['Paharpur Lodge', 'Green Valley Resort'],
    'Faisalabad': ['Faisalabad Grand Hotel', 'City Star Inn'],
    'Multan': ['Multan Plaza Hotel', 'Royal Residency'],
    'Gojra': ['Gojra Inn', 'Garden View Hotel'],
    'Phandar': ['Phandar Serenity Resort', 'Lake View Lodge'],
    'Gulmit': ['Gulmit Continental Hotel', 'Pamir View Inn'],
    'Liaquatpur': ['Liaquatpur Deluxe Hotel', 'Comfort Inn'],
    'Nawabshah': ['Nawabshah Regency', 'Sunset Inn'],
    'Lower Dir': ['Lower Dir Heights', 'Valley Retreat'],
    'Chor': ['Chor Serene Hotel', 'Hillside Lodge'],
    'Nubra Valley': ['Nubra Valley Resort', 'Desert Oasis'],
    'Talagang': ['Talagang Inn', 'Hill View Hotel'],
    'Hala': ['Hala Heritage Hotel', 'Riverside Lodge'],
    'Hattar': ['Hattar Heights', 'Green Meadows Resort'],
    'Pind Dadan Khan': ['Pind Dadan Khan Palace', 'Mountain Retreat'],
    'Abbottabad': ['Abbottabad Grand Hotel', 'Hilltop Lodge'],
    'Dadu': ['Dadu Serenity Resort', 'River View Inn'],
    'Gujranwala Cantonment': ['Cantonment Deluxe Hotel', 'Gujranwala Suites'],
    'Thall': ['Thall Grand Inn', 'Desert Oasis Resort'],
    'Dajal': ['Dajal Regency', 'Sunset Inn'],
    'Nankana Sahib': ['Nankana Sahib Heights', 'Divine Retreat'],
    'Jamshoro': ['Jamshoro Plaza Hotel', 'Riverside Inn'],
    'Swat': ['Swat Grand Resort', 'Mountain View Lodge'],
    'Barikot': ['Barikot Serene Hotel', 'Hillside Retreat'],
    'Juglot': ['Juglot Valley Resort', 'Panoramic View Inn'],
    'Peshawar': ['Peshawar Royal Hotel', 'City Center Inn'],
    'Garhi Yasin': ['Garhi Yasin Luxury Resort', 'Riverside Lodge'],
    'Daulatpur': ['Daulatpur Deluxe Hotel', 'Comfort Suites'],
    'Chawinda': ['Chawinda Heights', 'Green Meadows Resort'],
    'Chunian': ['Chunian Heritage Hotel', 'Riverside Retreat'],
    'Muzaffarabad': ['Muzaffarabad Grand Hotel', 'Hilltop Inn'],
    'Bannu': ['Bannu Serenity Resort', 'River View Lodge'],
    'Hunza Valley': ['Hunza Valley Heights', 'Valley Retreat'],
    'Bhawalnagar': ['Bhawalnagar Serene Hotel', 'Hillside Inn'],
    'Brogdan': ['Brogdan Valley Resort', 'Mountain Oasis'],
    'Chichawatni': ['Chichawatni Plaza Hotel', 'City Center Inn'],
    'Karak': ['Karak Grand Hotel', 'Mountain View Inn'],
    'Jatoi': ['Jatoi Deluxe Hotel', 'Comfort Suites'],
    'Doaba': ['Doaba Heritage Hotel', 'Riverside Retreat'],
    'Haripur': ['Haripur Grand Hotel', 'Hilltop Inn'],
    'Sahiwal': ['Sahiwal Serenity Resort', 'River View Lodge'],
    'Babusar': ['Babusar Heights', 'Valley Oasis'],
    'Vehari': ['Vehari Regency', 'Sunset Inn'],
    'Pakpattan': ['Pakpattan Serene Hotel', 'Hillside Lodge'],
    'Sherqilla': ['Sherqilla Valley Resort', 'Mountain View Oasis'],
    'Dera Murad Jamali': ['Dera Murad Jamali Plaza Hotel', 'City Center Inn'],
    'Battagram': ['Battagram Royal Hotel', 'Mountain Retreat'],
    'Gupis': ['Gupis Serenity Resort', 'River View Inn'],
    'Darel': ['Darel Grand Resort', 'Valley View Lodge'],
    'Chiniot': ['Chiniot Grand Hotel', 'Hilltop Inn'],
    'Kamoke': ['Kamoke Serene Hotel', 'Hillside Retreat'],
    'Jahanian Shah': ['Jahanian Shah Heights', 'Green Meadows Resort'],
    'Fort Abbas': ['Fort Abbas Heritage Hotel', 'Riverside Retreat'],
    'Bhakkar': ['Bhakkar Deluxe Hotel', 'Comfort Inn'],
    'Dhoraji': ['Dhoraji Plaza Hotel', 'City Center Inn'],
    'Dinga': ['Dinga Serenity Resort', 'River View Lodge'],
    'Khaplu': ['Khaplu Heights', 'Valley Oasis'],
    'Naltar': ['Naltar Regency', 'Sunset Inn'],
    'Hujra Shah Muqim': ['Hujra Shah Muqim Serene Hotel', 'Hillside Lodge'],
    'Takht Bhai': ['Takht Bhai Heritage Hotel', 'Riverside Retreat'],
    'Haroonabad': ['Haroonabad Grand Hotel', 'Hilltop Inn'],
    'Lalian': ['Lalian Serenity Resort', 'River View Inn'],
    'Thaley': ['Thaley Royal Hotel', 'City Center Inn'],
    'Astore': ['Astore Serene Hotel', 'Hillside Retreat'],
    'Dhanot': ['Dhanot Valley Resort', 'Mountain View Oasis'],
    'Shahdadkot': ['Shahdadkot Plaza Hotel', 'City Center Inn'],
    'Mattani': ['Mattani Grand Hotel', 'Mountain Retreat'],
    'Hunza': ['Hunza Serenity Resort', 'River View Lodge'],
    'Jalalpur Bhattian': ['Jalalpur Bhattian Heights', 'Green Meadows Resort'],
    'Gujrat': ['Gujrat Grand Hotel', 'Hilltop Inn'],
    'Murree': ['Murree Serene Resort', 'Mountain View Retreat'],
    'Chaman': ['Chaman Regency', 'Sunset Inn'],
    'Bhimbar': ['Bhimbar Heights', 'Valley Oasis'],
    'Bhawana': ['Bhawana Serene Hotel', 'Hillside Lodge'],
    'Gircha': ['Gircha Valley Resort', 'Mountain View Oasis'],
    'Gujar Khan': ['Gujar Khan Plaza Hotel', 'City Center Inn'],
    'Wah Cantonment': ['Wah Cantonment Grand Hotel', 'Hilltop Inn'],
    'Chak Jhumra': ['Chak Jhumra Serene Hotel', 'Hillside Retreat'],
    'Bhit Shah': ['Bhit Shah Heritage Hotel', 'Riverside Retreat'],
    'Sheikhupura': ['Sheikhupura Deluxe Hotel', 'Comfort Inn'],
    'Shakargarh': ['Shakargarh Plaza Hotel', 'City Center Inn'],
    'Gahkuch': ['Gahkuch Serenity Resort', 'River View Lodge'],
    'Attock': ['Attock Grand Hotel', 'Hilltop Inn'],
    'Lakki Marwat': ['Lakki Marwat Serene Resort', 'Mountain View Retreat'],
    'Jalalpur Jattan': ['Jalalpur Jattan Heights', 'Green Meadows Resort'],
    'Nowshera Virkan': ['Nowshera Virkan Regency', 'Sunset Inn'],
    'Pasrur': ['Pasrur Serene Hotel', 'Hillside Lodge'],
    'Dadhar': ['Dadhar Valley Resort', 'Mountain View Oasis'],
    'Mianwali Bangla': ['Mianwali Bangla Plaza Hotel', 'City Center Inn'],
    'Hari Pur': ['Hari Pur Grand Hotel', 'Mountain Retreat'],
    'Kasur': ['Kasur Serenity Resort', 'River View Lodge'],
    'Saidu Sharif': ['Saidu Sharif Heights', 'Valley Oasis'],
    'Kot Ghulam Muhammad': ['Kot Ghulam Muhammad Regency', 'Sunset Inn'],
    'Dunga Bunga': ['Dunga Bunga Serene Hotel', 'Hillside Lodge'],
    'Aliabad': ['Aliabad Heritage Hotel', 'Riverside Retreat'],
    'Larkana': ['Larkana Grand Hotel', 'Hilltop Inn'],
    'Khairpur Tamewali': ['Khairpur Tamewali Deluxe Hotel', 'Comfort Inn'],
    'Kahna': ['Kahna Plaza Hotel', 'City Center Inn'],
    'Gwadar': ['Gwadar Serene Resort', 'Sea View Retreat'],
    'Sust': ['Sust Heights', 'Valley Oasis'],
    'Nagar': ['Nagar Regency', 'Sunset Inn'],
    'Gujranwala': ['Gujranwala Grand Hotel', 'Hilltop Inn'],
    'Burewala': ['Burewala Serenity Resort', 'River View Lodge'],
    'Nowshera': ['Nowshera Serene Hotel', 'Hillside Retreat'],
    'Chak Azam Sahu': ['Chak Azam Sahu Heritage Hotel', 'Riverside Retreat'],
    'Pindi Gheb': ['Pindi Gheb Heights', 'Green Meadows Resort'],
    'Rawalpindi': ['Rawalpindi Plaza Hotel', 'City Center Inn'],
    'Mian Channu': ['Mian Channu Serene Hotel', 'Hillside Lodge'],
    'Daska': ['Daska Serenity Resort', 'River View Inn'],
    'Hafizabad': ['Hafizabad Plaza Hotel', 'City Center Inn'],
    'Dunyapur': ['Dunyapur Valley Resort', 'Mountain View Oasis'],
    'Kohistan': ['Kohistan Serene Hotel', 'Hillside Retreat'],
    'Kharmang':['Kharmang Heights', 'Valley Oasis'],
    'Kohlu': ['Kohlu Regency', 'Sunset Inn'],
    'Kot Addu': ['Kot Addu Serene Hotel', 'Hillside Lodge'],
    'Pishin': ['Pishin Heritage Hotel', 'Riverside Retreat'],
    'Qambar': ['Qambar Deluxe Hotel', 'Comfort Inn'],
    'Rajanpur': ['Rajanpur Plaza Hotel', 'City Center Inn'],
    'Ratodero': ['Ratodero Serene Resort', 'River View Lodge'],
    'Rohri': ['Rohri Grand Hotel', 'Hilltop Inn'],
    'Sadiqabad': ['Sadiqabad Serenity Resort', 'River View Inn'],
    'Sakrand': ['Sakrand Heights', 'Green Meadows Resort'],
    'Samarqand': ['Samarqand Serene Hotel', 'Hillside Retreat'],
    'Sambrial': ['Sambrial Heritage Hotel', 'Riverside Retreat'],
    'Samundri': ['Samundri Deluxe Hotel', 'Comfort Inn'],
    'Sanjawi': ['Sanjawi Plaza Hotel', 'City Center Inn'],
    'Sarai Alamgir': ['Sarai Alamgir Serene Resort', 'Mountain View Retreat'],
    'Sargodha': ['Sargodha Grand Hotel', 'Hilltop Inn'],
    'Shahdadpur': ['Shahdadpur Serene Hotel', 'Hillside Retreat'],
    'Shahpur': ['Shahpur Heights', 'Green Meadows Resort'],
    'Shahpur Chakar': ['Shahpur Chakar Heritage Hotel', 'Riverside Retreat'],
    'Shikarpur': ['Shikarpur Grand Hotel', 'Hilltop Inn'],
    'Sialkot': ['Sialkot Serenity Resort', 'River View Lodge'],
    'Sibi': ['Sibi Plaza Hotel', 'City Center Inn'],
    'Sukkur': ['Sukkur Heights', 'Green Meadows Resort'],
    'Surab': ['Surab Serene Hotel', 'Hillside Retreat'],
    'Talhar': ['Talhar Heritage Hotel', 'Riverside Retreat'],
    'Tando Adam': ['Tando Adam Deluxe Hotel', 'Comfort Inn'],
    'Tando Allahyar': ['Tando Allahyar Plaza Hotel', 'City Center Inn'],
    'Tando Muhammad Khan': ['Tando Muhammad Khan Serene Resort', 'River View Lodge'],
    'Tangi': ['Tangi Serene Hotel', 'Hillside Retreat'],
    'Tarbela': ['Tarbela Heights', 'Green Meadows Resort'],
    'Toba Tek Singh': ['Toba Tek Singh Grand Hotel', 'Hilltop Inn'],
    'Uch Sharif': ['Uch Sharif Serenity Resort', 'River View Lodge'],
    'Umarkot': ['Umarkot Serene Hotel', 'Hillside Retreat'],
    'Uthal': ['Uthal Heights', 'Green Meadows Resort'],
    'Vihari': ['Vihari Plaza Hotel', 'City Center Inn'],
    'Lahore': ['Lahore Royal Hotel', 'Mughal Heritage Inn', 'City Star Inn', 'Garden Retreat'],
    'Wazirabad': ['Wazirabad Serene Resort', 'River View Lodge'],
    'Islamabad': ['Islamabad Plaza Hotel', 'Capital View Lodge', 'Hilltop Inn', 'Green Meadows Resort'],
    'Zhob': ['Zhob Heights', 'Green Meadows Resort'],
    'Ziarat': ['Ziarat Serene Hotel', 'Hillside Retreat'],
    'Karachi': ['Karachi Grand Hotel', 'Ocean View Resort', 'City Center Inn', 'Palm Oasis Hotel']
}
